apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-disease-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skin-disease-backend
  template:
    metadata:
      labels:
        app: skin-disease-backend
    spec:
      containers:
      - name: skin-disease-backend
        image: skin-disease-backend:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: skin-disease-backend-service
spec:
  type: NodePort
  selector:
    app: skin-disease-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007  # NodePort range is 30000-32767
