apiVersion: v1
kind: Service
metadata:
  name: skin-disease-service
spec:
  type: NodePort
  selector:
    app: skin-disease-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000  # You can choose a port in the range 30000-32767
